// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_clean_code_version.test.ts.

/** The version of the `@ggdna/dna-clean-code` package. */
export const dnaCleanCodeVersion = '0.1.1';
